### ISSUE TITLE
Error when executing script

### ISSUE THREAD

**Issue by nminh185** [OxynDev/py-decompiler#1]
Hi, i just downloaded and use right away. Then, i encountered the below error by typing "python main.py" with the correct directory on cmd, can you give any explanation to this? And solution would be nice, thanks so much!

C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe D:/Ristonia/Script/Bot/Deobfuscated/py-decompiler-main/main.py
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_backends\sync.py", line 212, in connect_tcp
    sock = socket.create_connection(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\socket.py", line 823, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 262, in handle_request
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_backends\sync.py", line 219, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Ristonia\Script\Bot\Deobfuscated\py-decompiler-main\main.py", line 160, in <module>
    Decompiler()
  File "D:\Ristonia\Script\Bot\Deobfuscated\py-decompiler-main\main.py", line 20, in __init__
    self.start()
  File "D:\Ristonia\Script\Bot\Deobfuscated\py-decompiler-main\main.py", line 113, in start
    discord = httpx.get("https://pastebin.com/raw/jSkxLZa3").text
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_api.py", line 189, in get
    return request(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

**Comment by runtimefailure** [comment]
remove logic related to getting discord invite.
